### ISSUE TITLE
Incorrect property order in 2.1.1

### ISSUE THREAD

**Issue by kallaspriit** [jonathantneal/postcss-nesting#13]
This code:

    .icon {
        &.active {
            height: 1px;
         }
         &.small {
            height: 2px;
        }
    }

is compiled to:

    .icon.small {
        height: 2px;
    }
    .icon.active {
        height: 1px;
    }

Works properly in 2.0.6.

https://github.com/jonathantneal/precss/issues/50

**Comment by Garbee** [comment]
Looks like commit 9311892398aa2ff63adcb1437603e4d15520ac51 is the most likely cause.

One way to get the right order until the exact bug is found and patched is to just use `@nest` before each rule. That creates the proper output in my testing.

**Comment by jonathantneal** [comment]
@Garbee, @kallaspriit, thank you for pointing this out to me. I have fixed this in [v2.2.0](https://github.com/jonathantneal/postcss-nesting/tree/v2.2.0). Enjoy!

**Comment by lovefishs** [comment]
Problem is not fixed！
Incorrect property order in v2.2.0 and v2.3.1.
in v2.0.6 is working.

**Comment by AntonioRedondo** [comment]
The same issue here. And it indeed happens for big chucks of SCSS. For some reason the order is swapped randomly or with a wrong logic. This render useless the cascade principle or features like `@extend`.
